apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi  # Specify the storage capacity
  volumeMode: Filesystem  # or Block for raw block devices
  accessModes:
    - ReadWriteOnce  # Read-write access for a single node
  persistentVolumeReclaimPolicy: Retain  # or Delete
  storageClassName: standard  # Use a StorageClass, if applicable
  hostPath:
    path: /mnt/data  # Host path for the volume
