apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}

data:
  COLLIE_URL: {{ .Values.collie.url }}
  #API_URL: {{ .Values.collie.url }}/collie
  ES_URL: {{ .Values.es.url }}
  GRAFANA_URL: {{ .Values.grafana.url }}
  