apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  OAUTH_CSP_CLIENTID: {{ .Values.oauth.csp_clientid | b64enc }}
  OAUTH_CSP_CLIENTSECRET: {{ .Values.oauth.csp_clientsecret | b64enc }}
  OAUTH_GITLAB_CLIENTID: {{ .Values.oauth.gitlab_clientid | b64enc }}
  OAUTH_GITLAB_CLIENTSECRET: {{ .Values.oauth.gitlab_clientsecret | b64enc }}