apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-autoscaler
  namespace: collie-agent
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: collie
  
data:
  # Increase memory requests/limits by 256Mi for every 20 nodes. round_up(nodes/nodes_per_step)*step
  # For example, for 150 nodes: round_up(150/20)*256Mi=2048Mi

  # in case of large nodes, cores-per-step will ensure that we continue to scale the agent
  agent-autoscaler: |-
    {
      "agent": {
        "requests": {
          "memory": {
            "base": "0",
            "max": "8Gi",
            "step": "256Mi",
            "nodesPerStep": 20,
            "coresPerStep": 480
          }
        },
        "limits": {
          "memory": {
            "base": "0",
            "max": "8Gi",
            "step": "256Mi",
            "nodesPerStep": 20,
            "coresPerStep": 480
          }
        }
      }
    }