apiVersion: v1
kind: ResourceQuota
metadata:
  name: agent-critical-pods
  namespace: collie-agent
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: collie
spec:
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          # Required to ensure agent is always running to provide autoscaling capabilities.
          - system-cluster-critical