apiVersion: v1
kind: Secret
metadata:
  name: agent
  namespace: collie-agent
  labels:
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: agent
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/managed-by: collie
  
data:
  API_KEY: {{.ApiKey}}
  ES_KEY: {{.EsKey}}