---
# Shrink default JVM heap.
esJavaOpts: "-Xmx256m -Xms256m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "1000m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1024M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  # for minikube: standard
  # for AKS: managed-csi
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M
